### ISSUE TITLE
Please remove 'sex or gender' retrieve from SB notebook

### ISSUE THREAD

**Issue by trashbirdecology** [skybristol/pylinkedcmd#1]
I suggest removing all fields relevant to 'sex or gender' in [this notebook](https://github.com/skybristol/pylinkedcmd/blob/dev/examples/Research%20record%20via%20WikiData.ipynb) wherever possible.

**Comment by skybristol** [comment]
Very good point! There's not really a reasonable way to remove reference to it from my notebook as the whole point of that exercise was to examine all of the properties that have made their way onto those items as claims.

However, it prompted me to go digging a bit to see how those properties made their way onto these items representing USGS people. The level of **control** we have over whether or not any given item in WikiData uses any given property in making a claim about an item is basically nil, which is part of the point of this whole exercise. To my knowledge, USGS did not directly create any of the items in WikiData representing USGS employees or affiliated people. They ended up in the data system via a pretty diverse set of circumstances. It's pretty cool, in a way, but it's kind of the "wild west" in terms of thinking of it as a managed data system. The cool thing is that every contribution is attributed, so we can track the history of how properties came to be added to records.

If we dig into that property a bit to see where it's used, 781 of the USGS person records have a "sex or gender" claim. Here's an example of the history on this for [Christopher Ellison](https://www.wikidata.org/w/index.php?title=Q57408490&action=history). That shows that the sex or gender property set to male for this item was contributed on 6 May, 2019 by [User:VIGNERON](https://www.wikidata.org/wiki/User:VIGNERON). At the same time, a reference was added indicating that the value was inferred from a "[male given name](https://www.wikidata.org/wiki/Q12308941)." Wow! That's the real problem, right? Remarks in the contribution look like it was made with a script, potentially to every item that was an instance of human at that time with any name [here](https://www.wikidata.org/wiki/Special:WhatLinksHere/Q12308941).

I'd say that User:VIGNERON made an ethical breach when making that contribution and may have violated something in the WikiData terms of reference. That user did practice good methods in adding the reference to the assertion as an inference, so we've got a caveat on the value. But that represents a real problem in the system and evidence of some level of gender and potentially value bias introduced into WikiData through these kinds of wholesale actions. The "sex or gender" [property](https://www.wikidata.org/wiki/Property:P21) in WikiData is an interesting one with a lot of [discussion](https://www.wikidata.org/wiki/Property_talk:P21). As you can imagine in a global context with so many potential cultures in play, something like this should be a place for much debate and discussion over time.

This does bring up a number of questions for us in this exercise. What should we do about something like this where claims are made about items that USGS has some interest in and potential influence over? I can imagine a number of things.

1. Whatever we might do corporately, it would be wise to inform current USGS staff who we've identified as having a WikiData identity that they might want to take "ownership" of those entities in the system and modify them as they see fit. We could develop and provide a set of recommended best practices or even go so far as providing a toolset to aid in applying those practices and monitoring items over time for "compliance." It might be best to do this through informal means such as a CDI presentation on the issue.
2. We could enter into the WikiData fray, refute the actions of User:VIGNERON, and run a script to undo all contributions made on USGS-affiliated items that we see as problematic. This might be best done as a socially conscious individual, not necessarily under the aegis of the USGS officially.
3. We could take corporate action as USGS to officially begin contributing to items that we see as affiliated with our organization and add new items as appropriate to round out our presence in the knowledge graph. In considering this direction the last few days as part of my exploration, I've thought that it would be wise to do that as a joint project with other individuals and organizations via ESIP where I think we could have very lively and productive conversations on matters just like this and come to good community understanding and direction.

**Comment by trashbirdecology** [comment]
**Solution # 1** seems nice, but who is going to field all the inquiries and provide the technical assistance for "taking ownership" of their WikiData entry?

**Solution # 2** is important -- taking this to WikiData and providing an immediate solution. But perhaps best to request input and assistance from e.g., ESIP or CDI members. Regardless of who does it, it should be done sooner than later. 

**Solution # 3** is equally, if not more important than the first two. But I am tending to disagree with your sentiment that this needs to be community driven. I can see where a wealth of supporters  can help influence change, but unless this is done immediately, is not a good solution imo. The human example you provided suggests the code automated at least one (but maybe all?) of the gender assignments using, and this is unacceptable. 

## **_Solution #3 is identified a simple and unacceptable problem that has what I suspect has a fairly straight forward solution -- remove all gender assignments unless self-assigned immediately._**

**Comment by skybristol** [comment]
I'm working up some type of presentation for an upcoming CDI meeting on this stuff, mostly from the perspective of the state of our USGS Corporate Master Data. I will show what our USGS footprint in Wikidata looks like as part of that and invite discussion on what we may want to do about it.

It's not so much a matter of my sentiment on this as it is the reality of what Wikidata is. The whole Wikiverse is a community-driven system that relies on active participation in various ways to create and maintain content across every part of the platform. User accounts that take massive action in the systems without community consent get booted and blacklisted all the time, and some aspects of the system are getting better governance controls put in place.

Fundamentally, a Wikidata representation of a specific human person is not the same as a Facebook or LinkedIn account and not even the same as records of authors created in ResearchGate, Academia.edu, or some of those kinds of systems as a result of harvesting pub metadata. Those online identities are built to be specifically taken over by an actual human individual as part of their profile. So, there's no real mechanism for a Wikidata item representing a person to become fully owned by that actual person for fully controlled self-assignment of claims/assertions.

If you look across the spectrum of Wikidata chatter, both inside and outside Wikiverse apps, you'll see that there is wide recognition that items describing human beings are different than other types of items and come with their own information management dynamics and implications. The global community is policing itself to some extent, and there have been high profile examples like Sarah Palin's page and the leaked info about her pick as McCain's running mate. The bottom line is that it's messy. But one good thing is that the provenance trace is sound enough that we can choose to explicitly not trust any given claim about anything based on the user account that made it or other factors.

So, looking at the third option again... If we as USGS do decide to jump into the fray and start making claims about things that we have influence over, it would be perfectly reasonable to refute (remove) the gender assignment assertion made on any person items in our sphere of influence. It would also be reasonable for you, me, and others to jump into community discussion on this issue and push for some larger community action.

**Comment by skybristol** [comment]
This was ultimately removed though it remains in history. Issues were raised but not fully resolved in Wikidata with users who had applied auto assignment of this property on records.
